// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPI.Data;

namespace WeatherAPI.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherAPI.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lisboa",
                            Date = new DateTime(2022, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 25.0
                        },
                        new
                        {
                            Id = 2,
                            City = "Lisboa",
                            Date = new DateTime(2022, 8, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 27.0
                        },
                        new
                        {
                            Id = 3,
                            City = "Lisboa",
                            Date = new DateTime(2022, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 28.0
                        },
                        new
                        {
                            Id = 4,
                            City = "Lisboa",
                            Date = new DateTime(2022, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 30.0
                        },
                        new
                        {
                            Id = 5,
                            City = "Lisboa",
                            Date = new DateTime(2022, 8, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 22.0
                        },
                        new
                        {
                            Id = 6,
                            City = "Porto",
                            Date = new DateTime(2022, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 20.0
                        },
                        new
                        {
                            Id = 7,
                            City = "Porto",
                            Date = new DateTime(2022, 8, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 22.0
                        },
                        new
                        {
                            Id = 8,
                            City = "Porto",
                            Date = new DateTime(2022, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 21.0
                        },
                        new
                        {
                            Id = 9,
                            City = "Porto",
                            Date = new DateTime(2022, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 23.0
                        },
                        new
                        {
                            Id = 10,
                            City = "Porto",
                            Date = new DateTime(2022, 8, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Temperature = 26.0
                        });
                });

            modelBuilder.Entity("WeatherAPI.Models.WeatherStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AverageTemp")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemp")
                        .HasColumnType("float");

                    b.Property<double>("MinTemp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
